AllCops:
# 除外するディレクトリ（自動生成されたファイル）
# デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - "tmp/**/*"
    - "config/initializers"
    - "vendor/**/*" # rubocop config/default.yml
    - "db/shcema.rb"
    - "node_modules/**/*"
    - "db/migrate/*.rb"
    - "bin/*"
    - "Gemfile"
  TargetRubyVersion: 2.6.5
  DisplayCopNames: true
  # SuggestExtensions: false

  Style/AndOr:
    EnforcedStyle: conditionals

  Style/AsciiComments:
    Enabled: false

  Style/Documentation:
    Enabled: false

  Style/NumericLiterals:
    Enabled: false

  Style/ClassAndModuleChildren:
    Enabled: false

  Bundler/OrderedGems:
    Enabled: false

  Lint/ShadowedException:
    Enabled: false
