version: '2'
services: 
  db:
    image: mysql:5.6 
    environment: 
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: root 
    volumes: 
      # データの永続化のため
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

  
  web:
    # コンテナ上でbinding.pryするために必要
    tty: true
    # コンテナ上でbinding.pryするために必要
    stdin_open: true
    build: .
    # 毎回サーバーを立ち上げる際pidファイルをkillする
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes: 
      # ローカルのディレクトリをコンテナ上にマウント
      - .:/izakaya_app
      # bundle installした後にbuildし直さなくても良くなる
      - bundle:/user/local/bundle
    ports: 
      - "3000:3000"
    links: 
      - db
    environment: 
      # 環境変数の読み込み
      - BASIC_AUTH_USER
      - BASIC_AUTH_PASSWORD

  
volumes: 
  mysql-data:
  # bundle installした後にbuildし直さなくてよくなる
  bundle:
  # public-data:
  # tmp-data:
  # log-data:
  # db-data:
