User.create(nickname: 'admin', 
            name: '管理者', 
            name_kana: 'カンリシャ', 
            age: 20, 
            phone_number: '1111111111',
            email: 'admin@admin.com',
            password: '000aaa', 
            password_confirmation: '000aaa', 
            admin: true)